version: '3.8'

services:
  users-posts-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-posts-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      # Mount data directory for SQLite database persistence
      - ./data:/app/data
      # Optional: Mount config for runtime configuration changes
      - ./config:/app/config:ro
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/users/count"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  app-data: